name: core-ci

on:
  push:
    branches: [ main ]
    paths:
      - "packages/core/**"
  pull_request:
    branches: [ main ]
    paths:
      - "packages/core/**"

jobs:
  test:
    name: core-lint-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          packages/core/.yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn
          
    - name: "install packages"
      run: cd packages/core && yarn install
      
    - name: "test"
      run: cd packages/core && yarn test --ci
